### PR TITLE
Make ipv4-to-int about 3x faster

### PR DESCRIPTION
**Pull request by lizmat**
- use native ints and bit operations
- use explicit conversion: that seems to be the major improvement

### CODE REVIEW

**Review by jmaslak — APPROVED** [review]
Wow, this is great.  If you are willing, I'd love to be pointed for documentation on the Int(Str) - the Int part makes sense to me but the (Str) part is new.

**Comment by jmaslak** [comment]
Measured performance improvement via timing test 03-random. Went from 18.5s CPU time to 17.9s CPU time on dev machine.

**Comment by lizmat** [comment]
https://docs.perl6.org/syntax/Coercion%20Type is probably a good entry point

**Comment by jmaslak** [comment]
That made the 03-random.t test take 11.7s down from 17.9s - about a 35% reduction in CPU time.

**Pull request merged**
